name: CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x gradlew  # <- Tambahkan izin eksekusi

      - name: Build Project
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Ensure Download Info
        uses: actions/download-artifact@v4

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/
          if-no-files-found: ignore  # Menghindari error jika laporan tidak ditemukan
